sudo: false
language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2

env:
  - REPORT_EXIT_STATUS=1 NO_INTERACTION=1 TESTS="--show-all" ax_cv_have_EV=yes ax_cv_have_PCRE=yes

before_install:
  - pushd ..
  - git clone https://github.com/pandax381/rlogd.git rlogd
  - cd rlogd
  - ./autogen.sh
  - ./configure
  - cd src
  - make librlog.a
  - popd

before_script:
  - phpize && ./configure --with-rlogd-src-dir=../rlogd/ && make

script:
  - make test | tee test-output.txt && grep 'TEST SUMMARY$' test-output.txt > /dev/null ; test $? '!=' 0
